In [1]:
import numpy as np

In [2]:
path_glasser = './data/neigh_matrix_Glasser.npy'
path_schafer = './data/neigh_matrix_Schaefer1000.npy'

matrix = np.load(path_schafer)

In [3]:
matrix.shape

(358, 358)

In [1]:
import sys
import os
base_dir = os.path.abspath('..')
sys.path.append(base_dir)

from graph_matching.data_loader.graph_loader import NetworkLoader
from graph_matching.data_loader.graph_loader import compute_mean_network

In [5]:
atlas = 'Schaefer1000'
structure_type='ses-01'
loader = NetworkLoader(atlas, structure_type, base_dir=base_dir+'/data_new_struct')

In [6]:
mean_network = compute_mean_network(loader=loader)

In [8]:
mean_network

(1000, 1000)

In [1]:
import sys
import os
import numpy as np
base_dir = os.path.abspath('..')
sys.path.append(base_dir)

from netalign.create_matrices import LMatrixCreater


In [2]:
L_matrix_creater = LMatrixCreater(type='binary')

In [6]:
A = np.array([[0, 0, 1], [0,1,1], [0,0,1]])
B = np.array([[1, 0, 0], [0,1,0], [0,0,1]])
print(A)
print(B)

[[0 0 1]
 [0 1 1]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
L_matrix_creater.construct_L(
    matrix_A=A,
    matrix_B=B
)

(0, 0, np.float64(2.0000000000000004))
(0, 1, np.float64(2.0000000000000004))
(0, 2, np.float64(0.0))
(1, 0, np.float64(2.9999999999999996))
(1, 1, np.float64(1.0))
(1, 2, np.float64(1.0))
(2, 0, np.float64(2.0000000000000004))
(2, 1, np.float64(2.0000000000000004))
(2, 2, np.float64(0.0))


array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [5]:
np.linalg.norm(A[:, 0] - A[0,:], 2)

np.float64(1.0)